name: desafio_capyba
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path: ^1.8.2
  path_provider: ^2.0.14
  camera: ^0.10.3+2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  iconsax: ^0.0.8
  firebase_storage: ^11.0.16
  cloud_firestore: ^4.4.5
  image_picker: ^0.8.7
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/